/*
 Avalara API Client Library
 * Avalara Shipping Verification for Beverage Alcohol
 *
 * API for evaluating transactions against direct-to-consumer Beverage Alcohol shipping regulations.  This API is currently in beta. 
 *
 * The version of SDK  : 22.1.0
 */

using System;
using System.IO;
using Xunit;

using Avalara.SDK.Client;
using Avalara.SDK.Helpers;
using Avalara.SDK.Api.EInvoicing.V1;

namespace Avalara.SDK.Test.Api
{
    /// <summary>
    ///  Class for testing ShippingVerificationApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class EInvoicingTests : IDisposable
    {
        private DocumentsApi instance;
        private ApiClient apiclient;
        public EInvoicingTests()
        {
            var root = Directory.GetCurrentDirectory();
            var basePath = root.Split("\\src\\")[0];
            var dotenv = Path.Combine(basePath, ".env");
            DotEnv.Load(dotenv);
            Configuration configuration = new Configuration
            {
                Environment = AvalaraEnvironment.Sandbox,
                BearerToken = Environment.GetEnvironmentVariable("BEARER_TOKEN"),
                AppName = "Test",
                AppVersion = "1.0",
                MachineName = "LocalBox"
            };

            apiclient = new ApiClient(configuration);

            instance = new DocumentsApi(apiclient);
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ShippingVerificationApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            Assert.IsType<DocumentsApi>(instance);
        }

        /// <summary>
        /// Test Get Documents
        /// </summary>
        [Fact]
        public void DocumentsTest()
        {
       
            var requestParameters = new GetDocumentListRequest();
            requestParameters.AvalaraVersion = "1.0";
            var response = instance.GetDocumentList(requestParameters);
            Assert.True(response != null);            
        }
    }
}