/*
 Avalara API Client Library
 * Avalara Shipping Verification for Beverage Alcohol
 *
 * API for evaluating transactions against direct-to-consumer Beverage Alcohol shipping regulations.  This API is currently in beta. 
 *
 * The version of SDK  : 22.1.0
 */

using System;
using System.IO;
using Xunit;

using Avalara.SDK.Client;
using Avalara.SDK.Helpers;
using Avalara.SDK.Api.Track1099.V2;
using System.Threading.Tasks;

namespace Avalara.SDK.Test.Api
{
    /// <summary>
    ///  Class for testing ShippingVerificationApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class Track1099Tests : IDisposable
    {
        private ApiClient apiclient;
        private IssuersApi issuersApi;
        public Track1099Tests()
        {
            var root = Directory.GetCurrentDirectory();
            var basePath = root.Split(new string[] { "\\src\\" }, StringSplitOptions.None)[0];
            var dotenv = Path.Combine(basePath, ".env");
            DotEnv.Load(dotenv);
            Configuration configuration = new Configuration
            {
                Environment = AvalaraEnvironment.QA,
                BearerToken = Environment.GetEnvironmentVariable("BEARER_TOKEN_TRACK1099"),
                AppName = "Test",
                AppVersion = "1.0",
                MachineName = "LocalBox"
            };

            apiclient = new ApiClient(configuration);
            issuersApi = new IssuersApi(apiclient);
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ShippingVerificationApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            Assert.IsType<IssuersApi>(issuersApi);
        }

        /// <summary>
        /// Test Get Documents
        /// </summary>
        [Fact]
        public async Task IssuersTest()
        {
            var response = await issuersApi.ApiIssuersGetAsync(new ApiIssuersGetRequest() { Top = 10, Skip = 0 });
            Assert.NotNull(response);
        }
    }
}